export const httpsCode = {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    BADREQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOTFOUND: 404,
    INTERNALSERVERERROR: 500,
    SERVICEUNAVAILABLE: 503
}

export const httpsMessage = {
    OK: "OK",
    CREATED: "CREATED",
    ACCEPTED: "ACCEPTED",
    BADREQUEST: "BADREQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOTFOUND: "NOTFOUND",
    INTERNALSERVERERROR: "INTERNAL SERVER ERROR",
    SERVICEUNAVAILABLE: "SERVICE UNAVAILABLE"
}
